local monarch = require "monarch.monarch"

function init(self)
	msg.post(".", "acquire_input_focus")
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.released then
		if gui.pick_node(gui.get_node("startgame_button"), action.x, action.y) then
			print("BUTTON***************************************")
			monarch.show(hash("popup"))
		end
	end
end

function on_reload(self)
	-- Add input-handling code here
	-- Remove this function if not needed
end
