local monarch = require "monarch.monarch"

function init(self)
	monarch.debug()
	msg.post("@render:/", "clear_color", { color = vmath.vector4(0.4, 0.6, 0.8,1.0) })
	msg.post("#", "init_monarch") -- wait until init() has been called for all screen.script instances
end

function on_message(self, message_id, message, sender)
	if message_id == hash("init_monarch") then
		monarch.show(hash("background"), { no_stack = true })
		monarch.show(hash("menu"))
	end
end
